### PR TITLE
fix(admin_panel): devise forget password

### PR DESCRIPTION
**Pull request by raj-aditya**

### CODE REVIEW

**Comment by mikevic** [comment]
@BALAJI-BALA @raj-aditya - move devise secret key to environment and also postmark

**Comment by raj-aditya** [comment]
> @BALAJI-BALA @raj-aditya - move devise secret key to environment and also postmark

@mikevic - secret_key and postmark api key  moved to credentials

**Comment by mikevic** [comment]
@BALAJI-BALA - this can be merged and deployed to staging/prod. Please make sure we recycle the credentials in Mentormind

**Comment by raj-aditya** [comment]
> @BALAJI-BALA - this can be merged and deployed to staging/prod. Please make sure we recycle the credentials in Mentormind

@mikevic postmark api key in mentormind changed

**Comment by raj-aditya** [comment]
> > @BALAJI-BALA - this can be merged and deployed to staging/prod. Please make sure we recycle the credentials in Mentormind
> 
> @mikevic @BALAJI-BALA  postmark api key in mentormind changed

**Pull request merged**
